name: 'Hello World'
description: 'Greet someone'
inputs:
  token:
    description: 'GitHub Access token'
    required: false
  repository:
    description: 'The repository name in full formar (owner/repo)'
    required: true
  type:
    description: 'Wanted release type (latest, stable, draft, nodraft)'
    required: true
outputs:
  release:
    description: 'Release tag'
  release_id:
    description: 'Release Github ID'
  browser_download_url:
    description: 'Release first asset download URL'
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.repository }}.
      shell: bash
    - name: Install powershell module
      shell: pwsh
      run: Install-Module -Name PowerShellForGitHub -Force
    - name: Get Release 1
      shell: pwsh
      run: |
        $latestRelease = Get-GitHubRelease -Uri https://github.com/${{ inputs.repository }} -Latest -AccessToken ${{ inputs.token }}
        Write-Host $latestRelease
        Write-Host "::set-output name=release::$($latestRelease)"
    - name: Get Release 2
      shell: pwsh
      run: .\GetRelease.ps1
    - id: random-number-generator
      run: echo "::set-output name=random-number::$(echo $RANDOM)"
      shell: bash